name = "sub1"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "3ba64f3c1170471ca724e4842bb91b48" }
]
